# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: github-credentials

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    git config --global user.email "AzurePipelines@fachi.net"
    git config --global user.name "Azure Pipelines"
    git config --global credential.helper "$BUILD_REPOSITORY_LOCALPATH/azure-pipelines-git-credential-helper.sh"
  displayName: 'setup git'

- script: |
    ./publish.sh
  displayName: 'build and publish'
  env:
    GIT_USERNAME: $(GIT_USERNAME)
    GIT_PASSWORD: $(GIT_PASSWORD)
